default_job = "check"

[jobs.check]
command = ["cargo", "check", "--color", "always"]
need_stdout = false

[jobs.clippy]
command = ["cargo", "clippy", "--color", "always"]
need_stdout = false

[jobs.test]
command = ["cargo", "test", "--color", "always", "--", "--color", "always"]
need_stdout = true

[jobs.doc]
command = ["cargo", "doc", "--color", "always", "--no-deps"]
need_stdout = false

[jobs.doc-open]
command = ["cargo", "doc", "--color", "always", "--no-deps", "--open"]
need_stdout = false
on_success = "back"

[jobs.run]
command = ["cargo", "run", "--color", "always"]
need_stdout = true
allow_warnings = true

# Build example site
[jobs.build]
command = [
  "cargo",
  "run",
  "--color",
  "always",
  "--",
  "build",
  "--source",
  "./tests/full/medium",
]
on_success = "quit"

# Develop Handlebars templates
[jobs.tpl]
command = [
  "cargo",
  "run",
  "--color",
  "always",
  "--features",
  "dev-handlebars-templates",
  "--",
  "serve",
  "--open",
  "--source",
  "./tests/full/medium",
]
need_stdout = true
allow_warnings = true
