[package]
name = "jelly"
version = "0.1.0"
edition = "2021"

[dependencies]
atty = "0.2.14"
base64 = "0.13.1"
clap = { version = "4.0.27", features = ["derive"] }
ctrlc = "3.4.0"
glob = "0.3.0"
gray_matter = "0.2.4"
handlebars = "4.3.5"
indoc = "1.0.8"
markdown-it = "0.4.0"
mime_guess = "2.0.4"
notify = "6.0.1"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.88"
serde_yaml = "0.9.14"
slug = "0.1.4"
syntect = "5.0.0"
tempfile = "3.8.0"
thiserror = "1.0.37"
tiny_http = "0.12.0"
titlecase = "2.2.1"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
