[package]
name = "jelly"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.13.1"
glob = "0.3.0"
gray_matter = "0.2.4"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.88"
thiserror = "1.0.37"
titlecase = "2.2.1"
