on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    environment: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/flake-checker-action@v5
        with:
          fail-mode: true
      - uses: DeterminateSystems/nix-installer-action@v10
      - uses: DeterminateSystems/magic-nix-cache-action@v4
      - run: nix flake check --all-systems
      - run: nix develop --command cargo fmt --check
      - run: nix develop --command cargo clippy
      - run: nix develop --command cargo build --release
      - run: nix develop --command cargo test
      - run: nix build
