on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Check Nix flake
        uses: DeterminateSystems/flake-checker-action@v5
        with:
          fail-mode: true
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v10
      - name: Set up Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v4
      - name: Check flake outputs
        run: nix flake check --all-systems
      - name: Check Rust formatting
        run: nix develop --command cargo fmt --check
      - name: Run Clippy
        run: nix develop --command cargo clippy
      - name: Rust build in release mode
        run: nix develop --command cargo build --release
      - name: Run Rust tests
        run: nix develop --command cargo test

  build:
    runs-on: ${{ matrix.systems.runner }}
    strategy:
      matrix:
        systems:
          - nix-system: aarch64-darwin
            runner: macos-latest-xlarge
          - nix-system: x86_64-darwin
            runner: macos-12
          - nix-system: aarch64-linux
            runner: namespace-profile-default-arm64
          - nix-system: x86_64-linux
            runner: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v10
      - name: Set up Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v4
      - name: Build jelly package for ${{ matrix.systems.nix-system }} on ${{ matrix.systems.runner }}
        run: nix build
