on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    environment: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: jelly-${{ hashFiles('**/Cargo.lock') }}
      - uses: DeterminateSystems/nix-installer@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          extra-conf: |
            binary-caches = https://cache.nixos.org https://${{ secrets.CACHIX_CACHE }}.cachix.org
            trusted-substituters = https://cache.nixos.org https://${{ secrets.CACHIX_CACHE }}.cachix.org
            trusted-public-keys = ${{ secrets.CACHIX_TRUSTED_PUBLIC_KEY }} ${{ secrets.NIXOS_PUBLIC_KEY }}
            trusted-users = root runner
      - name: Cachix setup
        run: |
          nix develop --command cachix authtoken ${{ secrets.CACHIX_AUTH_TOKEN }}
          nix develop --command cachix use ${{ secrets.CACHIX_CACHE }}
      #- run: nix develop --command cargo clippy
      - run: nix develop --command cargo fmt --check
      - run: nix develop --command cargo build --release
      - run: nix develop --command cargo test
      - run: |
          nix develop --profile jelly-dev-env
          nix develop --command cachix push ${{ secrets.CACHIX_CACHE }} jelly-dev-env
