on:
  push:
    branches:
      - main
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Check Nix flake
        uses: DeterminateSystems/flake-checker-action@v5
        with:
          fail-mode: true
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v10
      - name: Set up Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v4
      - name: Check flake outputs
        run: nix flake check --all-systems
      - name: Check Rust formatting
        run: nix develop --command cargo fmt --check
      - name: Run Clippy
        run: nix develop --command cargo clippy --all --all-targets --all-features --  -Dwarnings
      - name: Rust build in release mode
        run: nix develop --command cargo build --release
      - name: Run Rust tests
        run: nix develop --command cargo test --all --all-targets --all-features
      - name: Ensure no unused Rust dependencies
        run: nix develop --command cargo machete

  site:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v10
      - name: Set up Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v4
      - name: Build example site
        run: nix run . -- build --source ./tests/full/medium
      - name: Publish example site
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/
