name: "Publish every Git push to main to FlakeHub"
on:
  push:
    branches:
      - "main"
jobs:
  flakehub-publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "DeterminateSystems/nix-installer-action@v10"
      - uses: "DeterminateSystems/flakehub-push@v3"
        with:
          name: "lucperkins/jelly"
          rolling: true
          visibility: "private"
